name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [main] # o cualquier rama que uses para desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Create environment.ts
        run: |
          mkdir -p src/environments
          echo "export const environment = {" > src/environments/environment.ts
          echo "  production: true," >> src/environments/environment.ts
          echo "  giphyApiKey: '${{ secrets.GIPHYAPIKEY }}'" >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts


      - name: Build Angular app
        run: ng build --configuration=production --base-href="/<REPO_NAME>/"
        # reemplaza <REPO_NAME> por el nombre de tu repo, ej. testCICD

      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/gifs-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
